### PR TITLE
Release v0.5.0 (#593)

### PR DESCRIPTION
**Pull request by kpeluso**
## Summary

1. Implement a fix for incomplete migration of topic fields from the v0.4.0 upgrade.
2. Add additional RPC endpoint to allow for recalculating the inflation rate / target emission rate more often than once per month.
3. Update to use rewardable topics as active topics instead of using them separately.
4. Other miscellaneous minor fixes

## Link(s) to Ticket(s) or Issue(s) resolved by this PR

See
[Changelog.md](https://github.com/allora-network/allora-chain/blob/release-v0.5.0/CHANGELOG.md)

---------

## Are these changes tested and documented?

- [ ] If tested, please describe how. If not, why tests are not needed.
- [ ] If documented, please describe where. If not, describe why docs are not needed.
- [ ] Added to `Unreleased` section of `CHANGELOG.md`?

## Still Left Todo

*Fill this out if this is a Draft PR so others can help.*

### CODE REVIEW

**Comment by kpeluso** [comment]
release already got squashed...

**Comment by relyt29** [comment]
this is going to continue to happen so long as release is squashed when it goes into main

**Comment by relyt29** [comment]
I would favor a merge over a rebase on this one

**Comment by relyt29** [comment]
I don't understand why this PR is showing changes, `git diff origin/main origin/dev` shows 0 diff

**Comment by relyt29** [comment]
on my local, when I do the merge on my local dev branch and then check the diff there is no files changed.

I think github is shitting the bed on this

**Pull request merged**
