### PR TITLE
Update version names: v0.3.0->v0.4.0; v0.4.0->v0.4.1 . Register upgrade.

### PR DESCRIPTION
**Pull request by fernandofcampos**
## Purpose of Changes and their Description

Update version names: v0.3.0->v0.4.0; v0.4.0->v0.4.1 . Register upgrade.

## Are these changes tested and documented?

- [x] If tested, please describe how. If not, why tests are not needed.
- [ ] If documented, please describe where. If not, describe why docs are not needed.
- [ ] Added to `Unreleased` section of `CHANGELOG.md`?

## Still Left Todo

*Fill this out if this is a Draft PR so others can help.*

### CODE REVIEW

**Review by relyt29 — APPROVED** [review]
this looks good to me, we should check ConsensusVersion for the two modules as well

**Comment by relyt29** [comment]
just checked, emissions is good, mint needs a version bump

**Comment by relyt29** [comment]
actually, do we need to bump the module version if we're not doing a migration, just changing the RPC endpoints / business logic?

**Comment by fernandofcampos** [comment]
> actually, do we need to bump the module version if we're not doing a migration, just changing the RPC endpoints / business logic?

Apparently not, but the documentation is not 100% clear: https://docs.cosmos.network/v0.50/learn/advanced/upgrade#tracking-module-versions

They say, for instance: "For example, if the bank module was version 2 and an upgrade introduces bank module 3, the Cosmos SDK upgrades the bank module and runs the "version 2 to 3" migration script."

Not sure if this is just a trigger for Cosmos to run the migrations, or if there's something else. 

Since we changed the rpc endpoints, can we consider this a breaking change?

**Comment by relyt29** [comment]
I think it makes sense to keep the proto versioning in line with the module ConsensusVersion, though I see cosmos-sdk does not do that (their mint module is at consensus version 2, but their proto is at v1beta1)

Anyways I'm inclined to bump the version just on account

**Pull request merged**
